{% set version = '1.0.3' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-idefix
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/idefix_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/idefix/idefix_{{ version }}.tar.gz
  sha256: da6be80883091f0b82b41e95fb7afbda760d9fbc1c988cfa2a327e87c1cb124b

build:
  merge_build_host: True  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'            # [win]
    - '*/Rblas.dll'        # [win]
    - '*/Rlapack.dll'      # [win]

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ compiler('cxx') }}            # [not win]
    - {{ compiler('m2w64_cxx') }}      # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]

  host:
    - r-base
    - r-mass
    - r-rcpp >=0.12.18
    - r-rcpparmadillo
    - r-rdpack
    - r-dfidx
    - r-dplyr
    - r-scales
    - r-shiny
    - r-tmvtnorm
    # for compatibility with r-rcpparmadillo
    - llvm-openmp  # [osx]
    - libgomp      # [linux]
    - libblas
    - liblapack

  run:
    - r-base
    - {{ native }}gcc-libs         # [win]
    - r-mass
    - r-rcpp >=0.12.18
    - r-rcpparmadillo
    - r-rdpack
    - r-dfidx
    - r-dplyr
    - r-scales
    - r-shiny
    - r-tmvtnorm

test:
  commands:
    - $R -e "library('idefix')"           # [not win]
    - "\"%R%\" -e \"library('idefix')\""  # [win]

about:
  home: https://github.com/traets/idefix
  license: GPL-3.0-only
  summary: Generates efficient designs for discrete choice experiments based on the multinomial
    logit model, and individually adapted designs for the mixed multinomial logit model.
    The generated designs can be presented on screen and choice data can be gathered
    using a shiny application. Traets F, Sanchez G, and Vandebroek M (2020) <doi:10.18637/jss.v096.i03>.
  license_family: GPL3
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - conda-forge/r
    - tobiasraabe

# Package: idefix
# Type: Package
# Title: Efficient Designs for Discrete Choice Experiments
# Version: 1.0.3
# Authors@R: c( person("Frits", "Traets", email = "frits.traets@kuleuven.be", role = c("aut", "cre")), person("Daniel", "Gil", email = "danielgils@gmail.com", role = "ctb"))
# Maintainer: Frits Traets <frits.traets@kuleuven.be>
# Description: Generates efficient designs for discrete choice experiments based on the multinomial logit model, and individually adapted designs for the mixed multinomial logit model. The generated designs can be presented on screen and choice data can be gathered using a shiny application. Traets F, Sanchez G, and Vandebroek M (2020) <doi:10.18637/jss.v096.i03>.
# License: GPL-3
# Depends: R (>= 3.1.1), shiny
# LazyData: TRUE
# ByteCompile: TRUE
# Imports: dplyr, MASS, parallel, Rcpp (>= 0.12.18), Rdpack, stats, scales, tmvtnorm, utils, dfidx
# RoxygenNote: 7.1.2
# Encoding: UTF-8
# LinkingTo: Rcpp, RcppArmadillo
# RdMacros: Rdpack
# URL: https://github.com/traets/idefix
# Suggests: RSGHB, bayesm, testthat
# NeedsCompilation: yes
# Packaged: 2022-03-28 08:41:08 UTC; u0105757
# Author: Frits Traets [aut, cre], Daniel Gil [ctb]
# Repository: CRAN
# Date/Publication: 2022-03-28 12:10:05 UTC
